# Generated by Django 3.2.4 on 2021-06-14 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('remark', models.CharField(max_length=50, null=True)),
                ('modTime', models.DateTimeField(null=True)),
                ('creTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
